//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generico.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CLIENTE
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string ENDERECO { get; set; }
        public string CEP { get; set; }
        public string CIDADE { get; set; }
        public string CELULAR { get; set; }
        public string TELEFONE { get; set; }
        public string EMAIL { get; set; }
        public string CONTATO { get; set; }
        public string OBSERVACAO { get; set; }
    }
}
